export enum Qualities {
    Desenvolvedor = 1,
    PilotoBarco = 2,
    PilotoCarro = 3,
    PilotoMoto = 4,
    Medico = 5,
    Enfermeiro = 6,
    Bombeiro = 7,
    Policial = 8,
    Professor = 9,
    Engenheiro = 10,
    Eletricista = 11,
    Encanador = 12,
    Pintor = 13,
    Pedreiro = 14,
    Voluntario = 15,
    Logistico = 16,
}